services:
    api:
      container_name: dev_api
      ports: 
        - 3000:3000
      environment: 
        - RDS_HOST=db
        - RDS_USER=user
        - RDS_PASS=password
        - RDS_DB=myDb
      depends_on:
        - db
      command: bash -c "./wait-for-it.sh -t 0 db:3306 && npm install && npm run dev"
    db:
      container_name: dev_db
      volumes:
        - "dev_db:/var/lib/minesql/data"
      environment: 
        - MYSQL_USER=user
        - MYSQL_PASSWORD=password
        - MYSQL_HOST=localhost
        - MYSQL_DATABASE=myDb
volumes:
    dev_db: 